version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      nuget-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      devcontainer:
        patterns:
          - "*"
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      dotnet-sdk:
        patterns:
          - "*"
